/** Códigos del apéndice A.1 del OpenAPI V2.15.500, traducidos. */
export const ERROR_CODES: Record<string, string> = {
  "0": "Operación correcta.",
  LAP300001: "AppKey no encontrada.",
  LAP300002: "AppKey y SecretKey no coinciden.",
  LAP300003: "La cuenta de Hik-Partner Pro asociada a la AppKey no existe.",
  LAP000000: "Excepción del sistema.",
  LAP000001: "Error de parámetros.",
  LAP000002: "Recurso no encontrado.",
  LAP000003: "Recurso no encontrado.",
  LAP001005: "La cuenta está bloqueada.",
  LAP006001: "No se pudo añadir el dispositivo.",
  LAP006002: "Dispositivo desconocido.",
  LAP006006: "Excepción de red.",
  LAP006008: "El serial del dispositivo ya existe.",
  LAP006009: "El dispositivo no existe o la cuenta no tiene permiso sobre él.",
  LAP006012: "El sitio no existe.",
  LAP006013: "Sin permiso: el operador no es el propietario del sitio.",
  LAP006016: "Sin permiso para operar el sitio.",
  LAP006018: "Operación repetida, espera antes de reintentar.",
  LAP008001: "El sitio no existe o la cuenta no tiene permiso.",
  LAP008008: "Error de red.",
  LAP008077: "Sin permiso.",
  LAP033005: "No se pudo obtener el token.",
  LAP034000: "La cuenta no tiene permiso para acceder al dispositivo.",
  LAP034001: "La cuenta no tiene permiso para acceder al sitio.",
  LAP035001: "Recurso solicitado no encontrado.",
  LAP500001: "Servicio no disponible.",
  LAP500002: "El token está vacío.",
  LAP500003: "Formato de token inválido.",
  LAP500004: "Token expirado o incorrecto (vigencia de 7 días).",
  LAP500005: "Falló la verificación del token.",
  LAP500006: "No se pudo obtener la información.",
  LAP500007: "Se superó el número de llamadas permitidas.",
  LAP031002: "No se pudo subir el archivo.",
  LAP031007: "El archivo es demasiado grande.",
  LAP031008: "Archivo inválido.",
  LAP068001: "Otra búsqueda está en curso con la misma AppKey/SecretKey.",
  LAP068002: "No se pudieron obtener las alarmas.",
  VMS022554: "Los recursos físicos no existen.",
  VMS050020: "Error del servicio de vídeo (convergence-vms-video). No está documentado en el apéndice A.1.",
  VMS050028: "El nombre del archivo de audio tiene caracteres especiales.",
  VMS050034: "Dispositivo vinculado no encontrado.",
  EVZ10001: "Parámetro incorrecto.",
  EVZ10006: "La dirección IP está restringida.",
  EVZ10007: "Se alcanzó el límite de llamadas.",
  EVZ10013: "La aplicación no tiene permiso para llamar a esta API.",
  EVZ10020: "Falta el método de la petición.",
  EVZ10029: "Se superó la frecuencia de llamadas permitida.",
  EVZ20001: "El canal no existe.",
  EVZ20002: "El dispositivo no existe.",
  EVZ20006: "Excepción de red.",
  EVZ20007: "El dispositivo está desconectado.",
  EVZ20008: "El dispositivo no respondió a tiempo.",
  EVZ20014: "Serial de dispositivo incorrecto.",
  EVZ20015: "El dispositivo no admite esta función.",
  EVZ20018: "El dispositivo no está vinculado a la cuenta actual.",
  EVZ20024: "El dispositivo está desconectado y pertenece a otra cuenta.",
  EVZ20029: "El dispositivo está desconectado (añadido por esta cuenta).",
  EVZ49999: "Excepción de datos.",
  EVZ50000: "Excepción del servidor.",
  EVZ60012: "Error desconocido.",
  EVZ60019: "El cifrado está activado en el dispositivo.",
  EVZ60020: "El dispositivo no admite este comando.",
  EVZ60051: "Dispositivo no compatible.",
  EVZ60054: "La cuenta del dispositivo está bloqueada.",
  NO_SESSION: "No hay sesión activa en el laboratorio. Conecta tu API Key.",
  BAD_PATH: "Ruta no permitida por el proxy del laboratorio.",
  PROXY_ERROR: "El proxy no pudo contactar a Hik-Partner Pro.",
};

/** Pistas accionables para los fallos típicos del módulo de audio. */
const AUDIO_HINTS: Record<string, string> = {
  EVZ20007: "Comprueba en Dispositivos que el altavoz aparezca en línea antes de emitir.",
  EVZ20015: "El cut-in solo existe en IP Speaker (categoría 12 / subtipo 19); revisa la categoría del equipo.",
  EVZ60020: "El firmware del altavoz no expone este comando; actualízalo o pruébalo desde Hik-Partner Pro.",
  EVZ20002: "El serial no está en esta cuenta; selecciónalo del inventario en vez de escribirlo.",
  EVZ20018: "El equipo pertenece a otra cuenta o sitio compartido sin permiso de control.",
  LAP006009: "Tu AppKey no tiene permiso sobre ese dispositivo o el sitio no es tuyo.",
  EVZ10001: "Algún campo del cuerpo va fuera de rango: audioLevel [0,15], audioVolume [0,100], pace [0,100].",
  LAP000001: "Algún campo del cuerpo va fuera de rango o falta un obligatorio.",
  VMS050020:
    "El backend acepta la petición pero el altavoz no ejecuta el cut-in: suele ser un equipo sin la función habilitada, sin licencia de audio o con el firmware desactualizado. Usa «Probar variantes» para descartar el payload.",
  VMS050028:
    "Usa solo letras sin acentos, números, guion y guion bajo en el nombre; nada de espacios, tildes, ñ, paréntesis o signos.",
};

export function explainError(code?: string, context?: "audio") {
  if (!code) return "";
  const base = ERROR_CODES[code];
  const hint = context === "audio" ? AUDIO_HINTS[code] : undefined;
  if (!base && !hint) return "";
  return [base, hint].filter(Boolean).join(" ");
}
